import { CategoryConfig } from './types';

export const CATEGORIES: CategoryConfig[] = [
  {
    id: 'history',
    label: 'Histoire & Faits',
    description: 'Explorez le passé avec des anecdotes vérifiées et fascinantes.',
    colors: {
      bg: 'bg-amber-100',
      text: 'text-amber-950',
      accent: 'text-amber-700',
      border: 'border-amber-300',
      gradientFrom: 'from-amber-500',
      gradientTo: 'to-orange-600',
      button: 'bg-amber-600',
      buttonHover: 'hover:bg-amber-700',
      chatBubbleUser: 'bg-amber-600 text-white',
      chatBubbleAi: 'bg-amber-200 text-amber-950',
    },
    iconName: 'history',
    promptTopic: "l'Histoire, en se concentrant sur des événements méconnus, des paradoxes historiques ou des moments charnières oubliés",
  },
  {
    id: 'complex',
    label: 'Relations Complexes',
    description: 'Analysez les dynamiques humaines et les dilemmes sociaux.',
    colors: {
      bg: 'bg-violet-100',
      text: 'text-violet-950',
      accent: 'text-violet-700',
      border: 'border-violet-300',
      gradientFrom: 'from-violet-500',
      gradientTo: 'to-purple-700',
      button: 'bg-violet-600',
      buttonHover: 'hover:bg-violet-700',
      chatBubbleUser: 'bg-violet-600 text-white',
      chatBubbleAi: 'bg-violet-200 text-violet-950',
    },
    iconName: 'brain',
    promptTopic: "les relations humaines complexes, la psychologie sociale, les dynamiques de pouvoir subtiles ou les malentendus culturels",
  },
  {
    id: 'love',
    label: 'Relations Amoureuses',
    description: 'Discussions profondes sur l\'amour, l\'attachement et le couple.',
    colors: {
      bg: 'bg-rose-100',
      text: 'text-rose-950',
      accent: 'text-rose-700',
      border: 'border-rose-300',
      gradientFrom: 'from-rose-500',
      gradientTo: 'to-pink-700',
      button: 'bg-rose-600',
      buttonHover: 'hover:bg-rose-700',
      chatBubbleUser: 'bg-rose-600 text-white',
      chatBubbleAi: 'bg-rose-200 text-rose-950',
    },
    iconName: 'heart',
    promptTopic: "les relations amoureuses, les langages de l'amour, la gestion des conflits dans le couple ou l'évolution des sentiments",
  },
  {
    id: 'tense',
    label: 'Situations Tendues',
    description: 'Désamorcer les conflits et comprendre les désaccords.',
    colors: {
      bg: 'bg-cyan-100',
      text: 'text-cyan-950',
      accent: 'text-cyan-700',
      border: 'border-cyan-300',
      gradientFrom: 'from-cyan-500',
      gradientTo: 'to-teal-700',
      button: 'bg-cyan-600',
      buttonHover: 'hover:bg-cyan-700',
      chatBubbleUser: 'bg-cyan-600 text-white',
      chatBubbleAi: 'bg-cyan-200 text-cyan-950',
    },
    iconName: 'storm',
    promptTopic: "la résolution de conflit, la diplomatie personnelle, la gestion de la colère ou les conversations difficiles mais nécessaires",
  },
  {
    id: 'random',
    label: 'L\'Imprévu',
    description: 'Laissez le hasard décider. Philosophie, science ou art.',
    colors: {
      bg: 'bg-slate-200',
      text: 'text-slate-900',
      accent: 'text-slate-700',
      border: 'border-slate-300',
      gradientFrom: 'from-slate-700',
      gradientTo: 'to-black',
      button: 'bg-slate-900',
      buttonHover: 'hover:bg-slate-800',
      chatBubbleUser: 'bg-slate-900 text-white',
      chatBubbleAi: 'bg-slate-300 text-slate-900',
    },
    iconName: 'dice',
    promptTopic: "un sujet totalement aléatoire mais fascinant (philosophie, science, art, futurisme, dilemme moral)",
  },
];